PATH %PATH%;C:\TMP
PATH %PATH%;C:\TMP\TC
PATH %PATH%;C:\TOOLS
PATH %PATH%;C:\VENDOR\CWSDPMI
PATH %PATH%;C:\VENDOR\NASM
PATH %PATH%;C:\VENDOR\PERL\BIN
PATH %PATH%;C:\VENDOR\WATCOM\BINW

SET PERL5LIB=C:\VENDOR\PERL\LIB\PERL5

SET INCLUDE=C:\VENDOR\WATCOM\H
SET WATCOM=C:\VENDOR\WATCOM
SET EDPATH=C:\VENDOR\WATCOM\EDDAT
SET WIPFC=C:\VENDOR\WATCOM\WIPFC

SET DOS16M=:6M
