/* apps/2048.c */
extern app_st app_2048;
/* apps/bjack.c */
extern app_st app_blackjack;
/* apps/clock.c */
extern app_st app_clock;
/* apps/fonts.c */
extern app_st app_fonts;
/* apps/freecell.c */
extern app_st app_freecell;
/* apps/keys.c */
extern app_st app_keys;
/* apps/klondike.c */
extern app_st app_klondike;
/* apps/launcher.c */
extern app_st app_launcher;
/* apps/mahjong.c */
extern app_st app_mahjong;
/* apps/mines.c */
extern app_st app_mines;
/* apps/pairs.c */
extern app_st app_pairs;
/* apps/setup.c */
extern app_st app_setup;
/* apps/snake.c */
extern app_st app_snake;
/* apps/sounds.c */
extern app_st app_sounds;
/* apps/tetris.c */
extern app_st app_tetris;
