/* apps/calendar.c */
extern app_st app_calendar;
/* apps/clock.c */
extern app_st app_clock;
/* apps/colors.c */
extern app_st app_colors;
/* apps/fonts.c */
extern app_st app_fonts;
/* apps/panel.c */
extern app_st app_panel;
/* apps/snake.c */
extern app_st app_snake;
